### ISSUE TITLE
MOONPAY_TEST_SECRET

### ISSUE THREAD

**Issue by anmolats** [nova-wallet/nova-android-app#1]
Caused by: java.util.NoSuchElementException: No secret MOONPAY_TEST_SECRET found

getting issue while integrate

**Comment by valentunn** [comment]
Hey! Sorry for not adding it to the how-to-run instructions. You should edit your `local.properties` file and include the following `MOONPAY_TEST_SECRET=stub`. You can also obtain real moonpay key and use it if you need moonpay to work
